[ids]
*
m:1d57:fa61
1d57:fa60:ad87ece0
# [global]
# layer_indicator = 1

[main]
capslock = overload(hyper, esc)
# capslock = layer(hyper)

[hyper]
# capslock = toggle(main)
h = left
j = down
k = up
l = right

[control+shift]

[ids]
